import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1761513040459 implements MigrationInterface {
    name = 'InitSchema1761513040459'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`bundles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(150) NOT NULL, \`description\` text NULL, \`price\` decimal(10,2) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bundle_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`item_type\` enum ('school', 'course') NOT NULL, \`bundle_id\` int NULL, \`school_id\` int NULL, \`course_id\` int NULL, UNIQUE INDEX \`IDX_d4b40b08821e4ec1c20ccffe3a\` (\`bundle_id\`, \`item_type\`, \`school_id\`, \`course_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`courses\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`price\` decimal(10,2) NOT NULL DEFAULT '0.00', \`is_published\` tinyint NOT NULL DEFAULT '0', \`thumbnail\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`school_id\` int NULL, \`teacher_id\` int NULL, \`created_by\` int NULL, INDEX \`idx_courses_teacher\` (\`teacher_id\`), INDEX \`idx_courses_school\` (\`school_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`course_classes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`video_url\` varchar(255) NULL, \`zoom_link\` varchar(255) NULL, \`starts_at\` datetime NULL, \`duration_minutes\` int NOT NULL DEFAULT '0', \`order_index\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`course_id\` int NULL, INDEX \`idx_class_course\` (\`course_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`course_materials\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`type\` enum ('pdf', 'link', 'other') NOT NULL DEFAULT 'link', \`url\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`class_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`schools\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(150) NOT NULL, \`description\` text NULL, \`logo\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`events\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`price\` decimal(10,2) NOT NULL DEFAULT '0.00', \`event_date\` datetime NULL, \`zoom_link\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event_registrations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`event_id\` int NULL, \`user_id\` int NULL, \`payment_item_id\` int NULL, UNIQUE INDEX \`IDX_73e2fef1cef19c806dcd5a8c4f\` (\`event_id\`, \`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NULL, \`message\` text NULL, \`type\` enum ('system', 'subscription', 'referral', 'event', 'payment') NOT NULL DEFAULT 'system', \`is_read\` tinyint NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`user_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` decimal(10,2) NOT NULL, \`currency\` varchar(10) NOT NULL DEFAULT 'USD', \`status\` enum ('pending', 'completed', 'failed', 'refunded') NOT NULL DEFAULT 'pending', \`payment_method\` varchar(50) NULL, \`transaction_ref\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`payer_id\` int NULL, \`subscription_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`item_type\` enum ('plan', 'bundle', 'course', 'event') NOT NULL, \`item_id\` bigint NOT NULL, \`unit_price\` decimal(10,2) NOT NULL, \`quantity\` int NOT NULL DEFAULT '1', \`line_total\` decimal(10,2) NOT NULL, \`payment_id\` int NULL, INDEX \`idx_pi_payment\` (\`payment_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_entitlements\` (\`id\` int NOT NULL AUTO_INCREMENT, \`target_type\` enum ('school', 'course', 'bundle', 'event') NOT NULL, \`target_id\` bigint NOT NULL, \`start_date\` date NOT NULL, \`end_date\` date NULL, \`user_id\` int NULL, \`payment_item_id\` int NULL, UNIQUE INDEX \`IDX_3e5376d2a61e83523a31a635ce\` (\`user_id\`, \`target_type\`, \`target_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`plans\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`duration_months\` int NOT NULL, \`price\` decimal(10,2) NOT NULL, \`description\` text NULL, \`is_active\` tinyint NOT NULL DEFAULT '1', \`trial_days\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`plan_entitlements\` (\`id\` int NOT NULL AUTO_INCREMENT, \`target_type\` enum ('platform', 'school', 'course', 'bundle') NOT NULL, \`target_id\` bigint NULL, \`plan_id\` int NULL, UNIQUE INDEX \`IDX_415969a59fc36217fdf1f91f45\` (\`plan_id\`, \`target_type\`, \`target_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subscriptions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`start_date\` date NOT NULL, \`end_date\` date NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT '1', \`auto_renew\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`user_id\` int NULL, \`plan_id\` int NULL, INDEX \`idx_sub_active\` (\`is_active\`, \`end_date\`), INDEX \`idx_sub_user\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subscription_entitlements\` (\`id\` int NOT NULL AUTO_INCREMENT, \`target_type\` enum ('platform', 'school', 'course', 'bundle') NOT NULL, \`target_id\` bigint NULL, \`start_date\` date NOT NULL, \`end_date\` date NOT NULL, \`subscription_id\` int NULL, UNIQUE INDEX \`IDX_19d7ad227bb8540f0955ef0357\` (\`subscription_id\`, \`target_type\`, \`target_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`referrals\` (\`id\` int NOT NULL AUTO_INCREMENT, \`active\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`deactivated_at\` timestamp NULL, \`referrer_id\` int NULL, \`referred_id\` int NULL, UNIQUE INDEX \`IDX_8e9c41bf92c60b4daef09e4e37\` (\`referrer_id\`, \`referred_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`referral_commissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`period_month\` date NOT NULL, \`commission_amount\` decimal(10,2) NOT NULL, \`phase\` enum ('first_month', 'next_month') NOT NULL, \`status\` enum ('pending', 'payable', 'paid', 'canceled') NOT NULL DEFAULT 'pending', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`referrer_id\` int NULL, \`referred_id\` int NULL, \`payment_id\` int NULL, INDEX \`idx_comm_referred_period\` (\`referred_id\`, \`period_month\`), INDEX \`idx_comm_referrer_period\` (\`referrer_id\`, \`period_month\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`referral_configs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`default_max_referrals\` int NOT NULL DEFAULT '10', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`referral_policies\` (\`id\` int NOT NULL AUTO_INCREMENT, \`scope\` enum ('global', 'plan', 'product_type', 'product') NOT NULL, \`product_type\` enum ('course', 'bundle', 'event') NULL, \`product_id\` bigint NULL, \`first_month_user_pct\` decimal(5,2) NOT NULL DEFAULT '90.00', \`next_months_user_pct\` decimal(5,2) NOT NULL DEFAULT '10.00', \`include_events\` tinyint NOT NULL DEFAULT '0', \`active\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`plan_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`referral_slots\` (\`id\` int NOT NULL AUTO_INCREMENT, \`max_slots\` int NOT NULL, \`user_id\` int NULL, UNIQUE INDEX \`IDX_18868039aafdf61ca710363604\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(50) NOT NULL, \`description\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(150) NOT NULL, \`email\` varchar(150) NOT NULL, \`password\` varchar(255) NOT NULL, \`avatar\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_notification_settings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email_enabled\` tinyint NOT NULL DEFAULT '1', \`push_enabled\` tinyint NOT NULL DEFAULT '0', \`notify_expiring_subscription\` tinyint NOT NULL DEFAULT '1', \`user_id\` int NULL, UNIQUE INDEX \`IDX_52182ffd0f785e8256f8fcb4fd\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NULL, \`role_id\` int NULL, UNIQUE INDEX \`IDX_23ed6f04fe43066df08379fd03\` (\`user_id\`, \`role_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`bundles\` ADD CONSTRAINT \`FK_956309564537c5fc5716a5cc89f\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bundle_items\` ADD CONSTRAINT \`FK_204a2f0fd03ca0efbf9db586b7f\` FOREIGN KEY (\`bundle_id\`) REFERENCES \`bundles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bundle_items\` ADD CONSTRAINT \`FK_cdd093e240b43e4254c54ab4e76\` FOREIGN KEY (\`school_id\`) REFERENCES \`schools\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bundle_items\` ADD CONSTRAINT \`FK_e2691355ec7c1de34da69de40ee\` FOREIGN KEY (\`course_id\`) REFERENCES \`courses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`courses\` ADD CONSTRAINT \`FK_5d36fddafdb9cabd2df4178160d\` FOREIGN KEY (\`school_id\`) REFERENCES \`schools\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`courses\` ADD CONSTRAINT \`FK_fad76a730ee7f68d0a59652fb12\` FOREIGN KEY (\`teacher_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`courses\` ADD CONSTRAINT \`FK_16fcd8ab8bc042688984d5b3934\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`course_classes\` ADD CONSTRAINT \`FK_ef4bfab47f6604951290cf1c00f\` FOREIGN KEY (\`course_id\`) REFERENCES \`courses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`course_materials\` ADD CONSTRAINT \`FK_c2df7572365068c45a02901ca83\` FOREIGN KEY (\`class_id\`) REFERENCES \`course_classes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`schools\` ADD CONSTRAINT \`FK_ef03dfb02768757b2a35dc44325\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`events\` ADD CONSTRAINT \`FK_1a259861a2ce114f074b366eed2\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_registrations\` ADD CONSTRAINT \`FK_28b0a253c87a80a4b013c437f7d\` FOREIGN KEY (\`event_id\`) REFERENCES \`events\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_registrations\` ADD CONSTRAINT \`FK_e42ba7c85b05c49c8de4f360543\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_registrations\` ADD CONSTRAINT \`FK_5a5da3b7f93ffbe78327847c861\` FOREIGN KEY (\`payment_item_id\`) REFERENCES \`payment_items\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_02f8e8d4094492641ad95010ca1\` FOREIGN KEY (\`payer_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_75848dfef07fd19027e08ca81d2\` FOREIGN KEY (\`subscription_id\`) REFERENCES \`subscriptions\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_items\` ADD CONSTRAINT \`FK_c03172d6a1edb318ab03bdbb883\` FOREIGN KEY (\`payment_id\`) REFERENCES \`payments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_entitlements\` ADD CONSTRAINT \`FK_b3457fc9de1ad215cd1d0eac77c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_entitlements\` ADD CONSTRAINT \`FK_a42dd452a74bef9f60f5892df05\` FOREIGN KEY (\`payment_item_id\`) REFERENCES \`payment_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plan_entitlements\` ADD CONSTRAINT \`FK_1dda069e23e5d1e5da37a06b06e\` FOREIGN KEY (\`plan_id\`) REFERENCES \`plans\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` ADD CONSTRAINT \`FK_d0a95ef8a28188364c546eb65c1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` ADD CONSTRAINT \`FK_e45fca5d912c3a2fab512ac25dc\` FOREIGN KEY (\`plan_id\`) REFERENCES \`plans\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subscription_entitlements\` ADD CONSTRAINT \`FK_366247251ca1d05a352feef18e5\` FOREIGN KEY (\`subscription_id\`) REFERENCES \`subscriptions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_18af9fcaffac6d6d3b28130e149\` FOREIGN KEY (\`referrer_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_507a2818bf5524662b068c2e81c\` FOREIGN KEY (\`referred_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referral_commissions\` ADD CONSTRAINT \`FK_c1abd6e3f424382e310dc3c681c\` FOREIGN KEY (\`referrer_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referral_commissions\` ADD CONSTRAINT \`FK_7f6b9f50bf112d310257f96533e\` FOREIGN KEY (\`referred_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referral_commissions\` ADD CONSTRAINT \`FK_0327f1e019112b816c1b586b947\` FOREIGN KEY (\`payment_id\`) REFERENCES \`payments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referral_policies\` ADD CONSTRAINT \`FK_69a7ce9afb12206369344c80029\` FOREIGN KEY (\`plan_id\`) REFERENCES \`plans\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referral_slots\` ADD CONSTRAINT \`FK_18868039aafdf61ca7103636041\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_notification_settings\` ADD CONSTRAINT \`FK_52182ffd0f785e8256f8fcb4fd6\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_87b8888186ca9769c960e926870\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_b23c65e50a758245a33ee35fda1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_b23c65e50a758245a33ee35fda1\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_87b8888186ca9769c960e926870\``);
        await queryRunner.query(`ALTER TABLE \`user_notification_settings\` DROP FOREIGN KEY \`FK_52182ffd0f785e8256f8fcb4fd6\``);
        await queryRunner.query(`ALTER TABLE \`referral_slots\` DROP FOREIGN KEY \`FK_18868039aafdf61ca7103636041\``);
        await queryRunner.query(`ALTER TABLE \`referral_policies\` DROP FOREIGN KEY \`FK_69a7ce9afb12206369344c80029\``);
        await queryRunner.query(`ALTER TABLE \`referral_commissions\` DROP FOREIGN KEY \`FK_0327f1e019112b816c1b586b947\``);
        await queryRunner.query(`ALTER TABLE \`referral_commissions\` DROP FOREIGN KEY \`FK_7f6b9f50bf112d310257f96533e\``);
        await queryRunner.query(`ALTER TABLE \`referral_commissions\` DROP FOREIGN KEY \`FK_c1abd6e3f424382e310dc3c681c\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_507a2818bf5524662b068c2e81c\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_18af9fcaffac6d6d3b28130e149\``);
        await queryRunner.query(`ALTER TABLE \`subscription_entitlements\` DROP FOREIGN KEY \`FK_366247251ca1d05a352feef18e5\``);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` DROP FOREIGN KEY \`FK_e45fca5d912c3a2fab512ac25dc\``);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` DROP FOREIGN KEY \`FK_d0a95ef8a28188364c546eb65c1\``);
        await queryRunner.query(`ALTER TABLE \`plan_entitlements\` DROP FOREIGN KEY \`FK_1dda069e23e5d1e5da37a06b06e\``);
        await queryRunner.query(`ALTER TABLE \`purchase_entitlements\` DROP FOREIGN KEY \`FK_a42dd452a74bef9f60f5892df05\``);
        await queryRunner.query(`ALTER TABLE \`purchase_entitlements\` DROP FOREIGN KEY \`FK_b3457fc9de1ad215cd1d0eac77c\``);
        await queryRunner.query(`ALTER TABLE \`payment_items\` DROP FOREIGN KEY \`FK_c03172d6a1edb318ab03bdbb883\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_75848dfef07fd19027e08ca81d2\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_02f8e8d4094492641ad95010ca1\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_9a8a82462cab47c73d25f49261f\``);
        await queryRunner.query(`ALTER TABLE \`event_registrations\` DROP FOREIGN KEY \`FK_5a5da3b7f93ffbe78327847c861\``);
        await queryRunner.query(`ALTER TABLE \`event_registrations\` DROP FOREIGN KEY \`FK_e42ba7c85b05c49c8de4f360543\``);
        await queryRunner.query(`ALTER TABLE \`event_registrations\` DROP FOREIGN KEY \`FK_28b0a253c87a80a4b013c437f7d\``);
        await queryRunner.query(`ALTER TABLE \`events\` DROP FOREIGN KEY \`FK_1a259861a2ce114f074b366eed2\``);
        await queryRunner.query(`ALTER TABLE \`schools\` DROP FOREIGN KEY \`FK_ef03dfb02768757b2a35dc44325\``);
        await queryRunner.query(`ALTER TABLE \`course_materials\` DROP FOREIGN KEY \`FK_c2df7572365068c45a02901ca83\``);
        await queryRunner.query(`ALTER TABLE \`course_classes\` DROP FOREIGN KEY \`FK_ef4bfab47f6604951290cf1c00f\``);
        await queryRunner.query(`ALTER TABLE \`courses\` DROP FOREIGN KEY \`FK_16fcd8ab8bc042688984d5b3934\``);
        await queryRunner.query(`ALTER TABLE \`courses\` DROP FOREIGN KEY \`FK_fad76a730ee7f68d0a59652fb12\``);
        await queryRunner.query(`ALTER TABLE \`courses\` DROP FOREIGN KEY \`FK_5d36fddafdb9cabd2df4178160d\``);
        await queryRunner.query(`ALTER TABLE \`bundle_items\` DROP FOREIGN KEY \`FK_e2691355ec7c1de34da69de40ee\``);
        await queryRunner.query(`ALTER TABLE \`bundle_items\` DROP FOREIGN KEY \`FK_cdd093e240b43e4254c54ab4e76\``);
        await queryRunner.query(`ALTER TABLE \`bundle_items\` DROP FOREIGN KEY \`FK_204a2f0fd03ca0efbf9db586b7f\``);
        await queryRunner.query(`ALTER TABLE \`bundles\` DROP FOREIGN KEY \`FK_956309564537c5fc5716a5cc89f\``);
        await queryRunner.query(`DROP INDEX \`IDX_23ed6f04fe43066df08379fd03\` ON \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_52182ffd0f785e8256f8fcb4fd\` ON \`user_notification_settings\``);
        await queryRunner.query(`DROP TABLE \`user_notification_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_18868039aafdf61ca710363604\` ON \`referral_slots\``);
        await queryRunner.query(`DROP TABLE \`referral_slots\``);
        await queryRunner.query(`DROP TABLE \`referral_policies\``);
        await queryRunner.query(`DROP TABLE \`referral_configs\``);
        await queryRunner.query(`DROP INDEX \`idx_comm_referrer_period\` ON \`referral_commissions\``);
        await queryRunner.query(`DROP INDEX \`idx_comm_referred_period\` ON \`referral_commissions\``);
        await queryRunner.query(`DROP TABLE \`referral_commissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_8e9c41bf92c60b4daef09e4e37\` ON \`referrals\``);
        await queryRunner.query(`DROP TABLE \`referrals\``);
        await queryRunner.query(`DROP INDEX \`IDX_19d7ad227bb8540f0955ef0357\` ON \`subscription_entitlements\``);
        await queryRunner.query(`DROP TABLE \`subscription_entitlements\``);
        await queryRunner.query(`DROP INDEX \`idx_sub_user\` ON \`subscriptions\``);
        await queryRunner.query(`DROP INDEX \`idx_sub_active\` ON \`subscriptions\``);
        await queryRunner.query(`DROP TABLE \`subscriptions\``);
        await queryRunner.query(`DROP INDEX \`IDX_415969a59fc36217fdf1f91f45\` ON \`plan_entitlements\``);
        await queryRunner.query(`DROP TABLE \`plan_entitlements\``);
        await queryRunner.query(`DROP TABLE \`plans\``);
        await queryRunner.query(`DROP INDEX \`IDX_3e5376d2a61e83523a31a635ce\` ON \`purchase_entitlements\``);
        await queryRunner.query(`DROP TABLE \`purchase_entitlements\``);
        await queryRunner.query(`DROP INDEX \`idx_pi_payment\` ON \`payment_items\``);
        await queryRunner.query(`DROP TABLE \`payment_items\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_73e2fef1cef19c806dcd5a8c4f\` ON \`event_registrations\``);
        await queryRunner.query(`DROP TABLE \`event_registrations\``);
        await queryRunner.query(`DROP TABLE \`events\``);
        await queryRunner.query(`DROP TABLE \`schools\``);
        await queryRunner.query(`DROP TABLE \`course_materials\``);
        await queryRunner.query(`DROP INDEX \`idx_class_course\` ON \`course_classes\``);
        await queryRunner.query(`DROP TABLE \`course_classes\``);
        await queryRunner.query(`DROP INDEX \`idx_courses_school\` ON \`courses\``);
        await queryRunner.query(`DROP INDEX \`idx_courses_teacher\` ON \`courses\``);
        await queryRunner.query(`DROP TABLE \`courses\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4b40b08821e4ec1c20ccffe3a\` ON \`bundle_items\``);
        await queryRunner.query(`DROP TABLE \`bundle_items\``);
        await queryRunner.query(`DROP TABLE \`bundles\``);
    }

}
