import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1761373519091 implements MigrationInterface {
    name = 'InitSchema1761373519091'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`detraction_catalog\` (\`code\` varchar(10) NOT NULL, \`description\` varchar(255) NOT NULL, \`active\` tinyint NOT NULL DEFAULT '1', PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`perception_catalog\` (\`code\` varchar(10) NOT NULL, \`description\` varchar(255) NOT NULL, \`active\` tinyint NOT NULL DEFAULT '1', PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tax_catalog\` (\`code\` varchar(10) NOT NULL, \`description\` varchar(255) NOT NULL, \`active\` tinyint NOT NULL DEFAULT '1', PRIMARY KEY (\`code\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`companies\` (\`id\` int NOT NULL AUTO_INCREMENT, \`ruc\` varchar(20) NOT NULL, \`taxRegime\` enum ('GENERAL', 'MYPE', 'ESPECIAL', 'NO_DOMICILIADO') NOT NULL DEFAULT 'GENERAL', \`legal_name\` varchar(255) NOT NULL, \`comercial_name\` varchar(255) NULL, \`address\` varchar(255) NULL, \`country_code\` varchar(2) NOT NULL DEFAULT 'PE', \`email\` varchar(255) NULL, \`phone\` varchar(50) NULL, \`logo_url\` varchar(255) NULL, \`certificate_path\` varchar(255) NULL, \`certificate_password\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_1fe1a1fe5eaf15ada69b1b2e99\` (\`ruc\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`establishments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(10) NOT NULL, \`address\` varchar(255) NOT NULL, \`ubigeo\` varchar(6) NULL, \`department\` varchar(100) NULL, \`province\` varchar(100) NULL, \`district\` varchar(100) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`companyId\` int NULL, UNIQUE INDEX \`IDX_ce25f853d71eb62860e58cc141\` (\`companyId\`, \`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`documentType\` enum ('1', '6', '0') NOT NULL, \`document_number\` varchar(20) NOT NULL, \`name\` varchar(255) NOT NULL, \`address\` varchar(255) NULL, \`email\` varchar(255) NULL, \`phone\` varchar(50) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`series\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` enum ('01', '03', '07', '08', 'RC', 'RA', 'RR', '09', '31') NOT NULL, \`prefix\` varchar(10) NOT NULL, \`current_number\` int NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`companyId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`documents\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` enum ('01', '03', '07', '08') NOT NULL, \`number\` int NOT NULL, \`full_number\` varchar(20) NULL, \`issue_date\` date NOT NULL, \`due_date\` date NULL, \`currency\` enum ('PEN', 'USD') NOT NULL DEFAULT 'PEN', \`payment_method\` enum ('contado', 'credito') NOT NULL DEFAULT 'contado', \`taxable_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`exonerated_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`unaffected_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`free_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`igv_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`isc_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`other_taxes_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`total_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`sunat_status\` enum ('PENDIENTE', 'ENVIADO', 'ACEPTADO', 'RECHAZADO', 'ANULADO') NOT NULL DEFAULT 'PENDIENTE', \`cdr_status\` varchar(50) NULL, \`cdr_observation\` text NULL, \`hash_cpe\` varchar(200) NULL, \`exchange_rate\` decimal(10,4) NOT NULL DEFAULT '1.0000', \`anticipation_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`has_perception\` tinyint NOT NULL DEFAULT 0, \`perception_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`perception_base\` decimal(15,2) NOT NULL DEFAULT '0.00', \`perception_percentage\` decimal(5,2) NOT NULL DEFAULT '0.00', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`companyId\` int NULL, \`establishmentId\` int NULL, \`customerId\` int NULL, \`seriesId\` int NULL, INDEX \`idx_documents_customer\` (\`customerId\`), INDEX \`idx_documents_company_type_date\` (\`companyId\`, \`type\`, \`issue_date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`item_code\` varchar(50) NULL, \`description\` varchar(500) NOT NULL, \`unit_measure\` varchar(10) NOT NULL DEFAULT 'NIU', \`quantity\` decimal(15,2) NOT NULL, \`unit_value\` decimal(15,5) NOT NULL, \`unit_price\` decimal(15,5) NOT NULL, \`discount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`subtotal\` decimal(15,2) NOT NULL, \`igv_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`isc_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`total\` decimal(15,2) NOT NULL, \`igv_type\` enum ('10', '20', '30', '40') NOT NULL DEFAULT '10', \`documentId\` int NULL, INDEX \`idx_items_document\` (\`documentId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_tax\` (\`id\` int NOT NULL AUTO_INCREMENT, \`tax_type\` varchar(10) NOT NULL, \`base_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`tax_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`percentage\` decimal(5,2) NOT NULL DEFAULT '0.00', \`documentId\` int NULL, \`taxCatalogCode\` varchar(10) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_legends\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(10) NOT NULL, \`value\` varchar(500) NOT NULL, \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_related\` (\`id\` int NOT NULL AUTO_INCREMENT, \`relation_type\` enum ('NC', 'ND', 'ANULACION', 'REFERENCIA') NOT NULL, \`reason\` varchar(255) NULL, \`reason_code\` varchar(10) NULL, \`documentId\` int NULL, \`relatedDocumentId\` int NULL, \`creditNoteReasonId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_perception\` (\`id\` int NOT NULL AUTO_INCREMENT, \`percentage\` decimal(5,2) NULL, \`amount\` decimal(15,2) NULL, \`base_amount\` decimal(15,2) NULL, \`documentId\` int NULL, \`perceptionCatalogCode\` varchar(10) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_detraction\` (\`id\` int NOT NULL AUTO_INCREMENT, \`percentage\` decimal(5,2) NOT NULL, \`detraction_amount\` decimal(15,2) NOT NULL, \`account_number\` varchar(30) NULL, \`documentId\` int NULL, \`detractionCatalogCode\` varchar(10) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_retention\` (\`id\` int NOT NULL AUTO_INCREMENT, \`retention_percentage\` decimal(5,2) NOT NULL, \`retained_amount\` decimal(15,2) NOT NULL, \`payment_amount\` decimal(15,2) NOT NULL, \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_status\` (\`id\` int NOT NULL AUTO_INCREMENT, \`status\` enum ('GENERADO', 'FIRMADO', 'ENVIADO', 'ACEPTADO', 'RECHAZADO', 'ANULADO') NOT NULL, \`description\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`documentId\` int NULL, INDEX \`idx_status_document_created\` (\`documentId\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`action\` varchar(100) NULL, \`message\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_files\` (\`id\` int NOT NULL AUTO_INCREMENT, \`xml_path\` varchar(255) NULL, \`zip_path\` varchar(255) NULL, \`cdr_path\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_allowances_charges\` (\`id\` int NOT NULL AUTO_INCREMENT, \`is_charge\` tinyint NOT NULL DEFAULT 0, \`reason\` varchar(255) NULL, \`amount\` decimal(15,2) NOT NULL, \`factor\` decimal(10,6) NULL, \`affects_taxable\` tinyint NOT NULL DEFAULT 1, \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`item_allowances_charges\` (\`id\` int NOT NULL AUTO_INCREMENT, \`is_charge\` tinyint NOT NULL DEFAULT 0, \`reason\` varchar(255) NULL, \`amount\` decimal(15,2) NOT NULL, \`factor\` decimal(10,6) NULL, \`documentItemId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_guides\` (\`id\` int NOT NULL AUTO_INCREMENT, \`guide_number\` varchar(20) NOT NULL, \`guide_type\` enum ('09', '31') NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_details\` (\`id\` int NOT NULL AUTO_INCREMENT, \`mode_of_transport\` varchar(50) NULL, \`transporter_ruc\` varchar(20) NULL, \`transporter_name\` varchar(255) NULL, \`vehicle_plate\` varchar(20) NULL, \`driver_license\` varchar(50) NULL, \`start_ubigeo\` varchar(6) NULL, \`start_address\` varchar(255) NULL, \`arrival_ubigeo\` varchar(6) NULL, \`arrival_address\` varchar(255) NULL, \`gross_weight\` decimal(10,3) NULL, \`packages\` int NULL, \`shipment_date\` date NULL, \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`credit_notes_reasons\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(10) NOT NULL, \`description\` varchar(255) NOT NULL, \`active\` tinyint NOT NULL DEFAULT '1', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`paid_amount\` decimal(18,2) NOT NULL, \`paid_date\` date NOT NULL, \`payment_method\` varchar(50) NULL, \`reference\` varchar(255) NULL, \`extra\` json NULL, \`documentId\` int NULL, \`installmentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`anticipations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`anticipation_number\` varchar(20) NULL, \`issue_date\` date NOT NULL, \`total_amount\` decimal(15,2) NOT NULL, \`balance_amount\` decimal(15,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'PEN', \`payment_method\` enum ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'OTROS') NOT NULL DEFAULT 'EFECTIVO', \`reference\` text NULL, \`status\` enum ('ACTIVO', 'APLICADO', 'ANULADO') NOT NULL DEFAULT 'ACTIVO', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`companyId\` int NULL, \`customerId\` int NULL, \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_anticipations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`applied_amount\` decimal(15,2) NOT NULL, \`documentId\` int NULL, \`anticipationId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`installments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`installment_number\` int NOT NULL, \`due_date\` date NOT NULL, \`amount\` decimal(15,2) NOT NULL, \`paid_amount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`payment_date\` date NULL, \`status\` enum ('PENDIENTE', 'PAGADO', 'VENCIDO', 'ANULADO') NOT NULL DEFAULT 'PENDIENTE', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`daily_summaries\` (\`id\` int NOT NULL AUTO_INCREMENT, \`summary_date\` date NOT NULL, \`identifier\` varchar(30) NOT NULL, \`sunat_ticket\` varchar(50) NULL, \`status\` enum ('GENERADO', 'ENVIADO', 'ACEPTADO', 'OBSERVADO', 'RECHAZADO') NOT NULL DEFAULT 'GENERADO', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`companyId\` int NULL, UNIQUE INDEX \`IDX_9bdd8a2e6bf511e33437c0b84b\` (\`companyId\`, \`summary_date\`, \`identifier\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`daily_summary_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`operation\` enum ('INCLUIR', 'MODIFICAR', 'ANULAR') NOT NULL DEFAULT 'INCLUIR', \`dailySummaryId\` int NULL, \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`void_communications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`void_date\` date NOT NULL, \`identifier\` varchar(30) NOT NULL, \`sunat_ticket\` varchar(50) NULL, \`status\` enum ('GENERADO', 'ENVIADO', 'ACEPTADO', 'OBSERVADO', 'RECHAZADO') NOT NULL DEFAULT 'GENERADO', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`companyId\` int NULL, UNIQUE INDEX \`IDX_1f4b32ed3d9e235dd9e6dbc146\` (\`companyId\`, \`void_date\`, \`identifier\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`void_communication_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reason\` varchar(255) NULL, \`voidCommunicationId\` int NULL, \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_audit_log\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` bigint NULL, \`action\` varchar(100) NOT NULL, \`notes\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`taxes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(10) NOT NULL, \`name\` varchar(100) NOT NULL, \`rate\` decimal(6,2) NOT NULL, \`applies_to\` enum ('line', 'document') NOT NULL DEFAULT 'line', \`active\` tinyint NOT NULL DEFAULT '1', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`detraction_rules\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(10) NOT NULL, \`description\` varchar(255) NULL, \`rate\` decimal(6,2) NOT NULL, \`threshold\` decimal(18,2) NOT NULL DEFAULT '0.00', \`active\` tinyint NOT NULL DEFAULT '1', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`currencies\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(3) NOT NULL, \`name\` varchar(50) NULL, \`symbol\` varchar(5) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_9f8d0972aeeb5a2277e40332d2\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`send_attempts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`attempt_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`transport\` varchar(20) NULL, \`request_xml\` mediumtext NULL, \`response_xml\` mediumtext NULL, \`http_status\` int NULL, \`error_message\` text NULL, \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sunat_responses\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sent_zip\` longblob NULL, \`sent_xml\` mediumtext NULL, \`response_zip\` longblob NULL, \`response_xml\` mediumtext NULL, \`response_code\` varchar(50) NULL, \`response_message\` text NULL, \`cdr_filename\` varchar(255) NULL, \`status\` enum ('OK', 'ERROR', 'PENDING') NOT NULL DEFAULT 'PENDING', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`documentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`establishments\` ADD CONSTRAINT \`FK_6951d1a6d6dfd80297e395a8dae\` FOREIGN KEY (\`companyId\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`series\` ADD CONSTRAINT \`FK_1d74b04f823841451db786df5d9\` FOREIGN KEY (\`companyId\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_6f0a96a5bd71aab8902c8c678b1\` FOREIGN KEY (\`companyId\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_5d2e25b8f5e198d6aebbce1acca\` FOREIGN KEY (\`establishmentId\`) REFERENCES \`establishments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_1cbf180163aa949282edd424a92\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_2af33de49ce5a87b88ef3861b31\` FOREIGN KEY (\`seriesId\`) REFERENCES \`series\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_items\` ADD CONSTRAINT \`FK_2e12be9e375d7d1c2730dd0c8fa\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_tax\` ADD CONSTRAINT \`FK_60096dac09ead0a290d68944479\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_tax\` ADD CONSTRAINT \`FK_76c23d6f605bbfd14d6a8d1447f\` FOREIGN KEY (\`taxCatalogCode\`) REFERENCES \`tax_catalog\`(\`code\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_legends\` ADD CONSTRAINT \`FK_ce2cfb46549e72b4c8f48403914\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_related\` ADD CONSTRAINT \`FK_1a1078e32f5df16946246d3992a\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_related\` ADD CONSTRAINT \`FK_cd99f00fb58e2aa9e4c2a42c6e2\` FOREIGN KEY (\`relatedDocumentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_related\` ADD CONSTRAINT \`FK_2af8de608dd329c615ba96e908e\` FOREIGN KEY (\`creditNoteReasonId\`) REFERENCES \`credit_notes_reasons\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_perception\` ADD CONSTRAINT \`FK_219406d737896fdf08527ca087f\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_perception\` ADD CONSTRAINT \`FK_e7e7310251fdfb4c2f5c63db436\` FOREIGN KEY (\`perceptionCatalogCode\`) REFERENCES \`perception_catalog\`(\`code\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_detraction\` ADD CONSTRAINT \`FK_9938e85b0e8eb42e2ca7c55f9c3\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_detraction\` ADD CONSTRAINT \`FK_ccd943f063dc654cb99e03fc4bc\` FOREIGN KEY (\`detractionCatalogCode\`) REFERENCES \`detraction_catalog\`(\`code\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_retention\` ADD CONSTRAINT \`FK_b508f339546216a52eb444d2ea8\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_status\` ADD CONSTRAINT \`FK_bf9b5115448f6194c9569ff4a23\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_logs\` ADD CONSTRAINT \`FK_726ad8e0b37380c94fd20177b8f\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_files\` ADD CONSTRAINT \`FK_4a33c7b4cad3c6b35e106b006d2\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_allowances_charges\` ADD CONSTRAINT \`FK_dea284e5a558471dde0667e3e4c\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`item_allowances_charges\` ADD CONSTRAINT \`FK_9bbfabfba9498122a9810e3792e\` FOREIGN KEY (\`documentItemId\`) REFERENCES \`document_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_guides\` ADD CONSTRAINT \`FK_e1263be2678d981d540564696d6\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` ADD CONSTRAINT \`FK_95edf5d97fcab2732aac1b65344\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_86b279ae02beb897abddf8514c1\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_ad038f1a0071dfcec8215129492\` FOREIGN KEY (\`installmentId\`) REFERENCES \`installments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`anticipations\` ADD CONSTRAINT \`FK_98aae97dbe2242da5a8919e612c\` FOREIGN KEY (\`companyId\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`anticipations\` ADD CONSTRAINT \`FK_f7a741227a4a943d3f01f353145\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`anticipations\` ADD CONSTRAINT \`FK_d3f11fbcf93c3547aaae1a48e1d\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_anticipations\` ADD CONSTRAINT \`FK_3332b154beafe4175c440c39212\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_anticipations\` ADD CONSTRAINT \`FK_0420f1a8f1811f701980a770a6c\` FOREIGN KEY (\`anticipationId\`) REFERENCES \`anticipations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`installments\` ADD CONSTRAINT \`FK_b04f1739d5174d3ddeacdc7bcb4\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`daily_summaries\` ADD CONSTRAINT \`FK_d5c74441d0741ecee7593f63d82\` FOREIGN KEY (\`companyId\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`daily_summary_items\` ADD CONSTRAINT \`FK_92068a45507eeade7892081e88d\` FOREIGN KEY (\`dailySummaryId\`) REFERENCES \`daily_summaries\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`daily_summary_items\` ADD CONSTRAINT \`FK_c05b9a562ac158b936d72d86dcc\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`void_communications\` ADD CONSTRAINT \`FK_c4861b32ad0e2418834b3e73f95\` FOREIGN KEY (\`companyId\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`void_communication_items\` ADD CONSTRAINT \`FK_228f7766f7595505b5143d5eca7\` FOREIGN KEY (\`voidCommunicationId\`) REFERENCES \`void_communications\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`void_communication_items\` ADD CONSTRAINT \`FK_6cc7e47f6041122a8eb7ea1c6ac\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_audit_log\` ADD CONSTRAINT \`FK_9d32a5c8346129a89bfd2f8f459\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`send_attempts\` ADD CONSTRAINT \`FK_66b95f975a04440959d07537a62\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sunat_responses\` ADD CONSTRAINT \`FK_b3c79f9e94179cbab92c0c5917d\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`sunat_responses\` DROP FOREIGN KEY \`FK_b3c79f9e94179cbab92c0c5917d\``);
        await queryRunner.query(`ALTER TABLE \`send_attempts\` DROP FOREIGN KEY \`FK_66b95f975a04440959d07537a62\``);
        await queryRunner.query(`ALTER TABLE \`document_audit_log\` DROP FOREIGN KEY \`FK_9d32a5c8346129a89bfd2f8f459\``);
        await queryRunner.query(`ALTER TABLE \`void_communication_items\` DROP FOREIGN KEY \`FK_6cc7e47f6041122a8eb7ea1c6ac\``);
        await queryRunner.query(`ALTER TABLE \`void_communication_items\` DROP FOREIGN KEY \`FK_228f7766f7595505b5143d5eca7\``);
        await queryRunner.query(`ALTER TABLE \`void_communications\` DROP FOREIGN KEY \`FK_c4861b32ad0e2418834b3e73f95\``);
        await queryRunner.query(`ALTER TABLE \`daily_summary_items\` DROP FOREIGN KEY \`FK_c05b9a562ac158b936d72d86dcc\``);
        await queryRunner.query(`ALTER TABLE \`daily_summary_items\` DROP FOREIGN KEY \`FK_92068a45507eeade7892081e88d\``);
        await queryRunner.query(`ALTER TABLE \`daily_summaries\` DROP FOREIGN KEY \`FK_d5c74441d0741ecee7593f63d82\``);
        await queryRunner.query(`ALTER TABLE \`installments\` DROP FOREIGN KEY \`FK_b04f1739d5174d3ddeacdc7bcb4\``);
        await queryRunner.query(`ALTER TABLE \`document_anticipations\` DROP FOREIGN KEY \`FK_0420f1a8f1811f701980a770a6c\``);
        await queryRunner.query(`ALTER TABLE \`document_anticipations\` DROP FOREIGN KEY \`FK_3332b154beafe4175c440c39212\``);
        await queryRunner.query(`ALTER TABLE \`anticipations\` DROP FOREIGN KEY \`FK_d3f11fbcf93c3547aaae1a48e1d\``);
        await queryRunner.query(`ALTER TABLE \`anticipations\` DROP FOREIGN KEY \`FK_f7a741227a4a943d3f01f353145\``);
        await queryRunner.query(`ALTER TABLE \`anticipations\` DROP FOREIGN KEY \`FK_98aae97dbe2242da5a8919e612c\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_ad038f1a0071dfcec8215129492\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_86b279ae02beb897abddf8514c1\``);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` DROP FOREIGN KEY \`FK_95edf5d97fcab2732aac1b65344\``);
        await queryRunner.query(`ALTER TABLE \`shipping_guides\` DROP FOREIGN KEY \`FK_e1263be2678d981d540564696d6\``);
        await queryRunner.query(`ALTER TABLE \`item_allowances_charges\` DROP FOREIGN KEY \`FK_9bbfabfba9498122a9810e3792e\``);
        await queryRunner.query(`ALTER TABLE \`document_allowances_charges\` DROP FOREIGN KEY \`FK_dea284e5a558471dde0667e3e4c\``);
        await queryRunner.query(`ALTER TABLE \`document_files\` DROP FOREIGN KEY \`FK_4a33c7b4cad3c6b35e106b006d2\``);
        await queryRunner.query(`ALTER TABLE \`document_logs\` DROP FOREIGN KEY \`FK_726ad8e0b37380c94fd20177b8f\``);
        await queryRunner.query(`ALTER TABLE \`document_status\` DROP FOREIGN KEY \`FK_bf9b5115448f6194c9569ff4a23\``);
        await queryRunner.query(`ALTER TABLE \`document_retention\` DROP FOREIGN KEY \`FK_b508f339546216a52eb444d2ea8\``);
        await queryRunner.query(`ALTER TABLE \`document_detraction\` DROP FOREIGN KEY \`FK_ccd943f063dc654cb99e03fc4bc\``);
        await queryRunner.query(`ALTER TABLE \`document_detraction\` DROP FOREIGN KEY \`FK_9938e85b0e8eb42e2ca7c55f9c3\``);
        await queryRunner.query(`ALTER TABLE \`document_perception\` DROP FOREIGN KEY \`FK_e7e7310251fdfb4c2f5c63db436\``);
        await queryRunner.query(`ALTER TABLE \`document_perception\` DROP FOREIGN KEY \`FK_219406d737896fdf08527ca087f\``);
        await queryRunner.query(`ALTER TABLE \`document_related\` DROP FOREIGN KEY \`FK_2af8de608dd329c615ba96e908e\``);
        await queryRunner.query(`ALTER TABLE \`document_related\` DROP FOREIGN KEY \`FK_cd99f00fb58e2aa9e4c2a42c6e2\``);
        await queryRunner.query(`ALTER TABLE \`document_related\` DROP FOREIGN KEY \`FK_1a1078e32f5df16946246d3992a\``);
        await queryRunner.query(`ALTER TABLE \`document_legends\` DROP FOREIGN KEY \`FK_ce2cfb46549e72b4c8f48403914\``);
        await queryRunner.query(`ALTER TABLE \`document_tax\` DROP FOREIGN KEY \`FK_76c23d6f605bbfd14d6a8d1447f\``);
        await queryRunner.query(`ALTER TABLE \`document_tax\` DROP FOREIGN KEY \`FK_60096dac09ead0a290d68944479\``);
        await queryRunner.query(`ALTER TABLE \`document_items\` DROP FOREIGN KEY \`FK_2e12be9e375d7d1c2730dd0c8fa\``);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_2af33de49ce5a87b88ef3861b31\``);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_1cbf180163aa949282edd424a92\``);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_5d2e25b8f5e198d6aebbce1acca\``);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_6f0a96a5bd71aab8902c8c678b1\``);
        await queryRunner.query(`ALTER TABLE \`series\` DROP FOREIGN KEY \`FK_1d74b04f823841451db786df5d9\``);
        await queryRunner.query(`ALTER TABLE \`establishments\` DROP FOREIGN KEY \`FK_6951d1a6d6dfd80297e395a8dae\``);
        await queryRunner.query(`DROP TABLE \`sunat_responses\``);
        await queryRunner.query(`DROP TABLE \`send_attempts\``);
        await queryRunner.query(`DROP INDEX \`IDX_9f8d0972aeeb5a2277e40332d2\` ON \`currencies\``);
        await queryRunner.query(`DROP TABLE \`currencies\``);
        await queryRunner.query(`DROP TABLE \`detraction_rules\``);
        await queryRunner.query(`DROP TABLE \`taxes\``);
        await queryRunner.query(`DROP TABLE \`document_audit_log\``);
        await queryRunner.query(`DROP TABLE \`void_communication_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f4b32ed3d9e235dd9e6dbc146\` ON \`void_communications\``);
        await queryRunner.query(`DROP TABLE \`void_communications\``);
        await queryRunner.query(`DROP TABLE \`daily_summary_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_9bdd8a2e6bf511e33437c0b84b\` ON \`daily_summaries\``);
        await queryRunner.query(`DROP TABLE \`daily_summaries\``);
        await queryRunner.query(`DROP TABLE \`installments\``);
        await queryRunner.query(`DROP TABLE \`document_anticipations\``);
        await queryRunner.query(`DROP TABLE \`anticipations\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP TABLE \`credit_notes_reasons\``);
        await queryRunner.query(`DROP TABLE \`shipping_details\``);
        await queryRunner.query(`DROP TABLE \`shipping_guides\``);
        await queryRunner.query(`DROP TABLE \`item_allowances_charges\``);
        await queryRunner.query(`DROP TABLE \`document_allowances_charges\``);
        await queryRunner.query(`DROP TABLE \`document_files\``);
        await queryRunner.query(`DROP TABLE \`document_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_status_document_created\` ON \`document_status\``);
        await queryRunner.query(`DROP TABLE \`document_status\``);
        await queryRunner.query(`DROP TABLE \`document_retention\``);
        await queryRunner.query(`DROP TABLE \`document_detraction\``);
        await queryRunner.query(`DROP TABLE \`document_perception\``);
        await queryRunner.query(`DROP TABLE \`document_related\``);
        await queryRunner.query(`DROP TABLE \`document_legends\``);
        await queryRunner.query(`DROP TABLE \`document_tax\``);
        await queryRunner.query(`DROP INDEX \`idx_items_document\` ON \`document_items\``);
        await queryRunner.query(`DROP TABLE \`document_items\``);
        await queryRunner.query(`DROP INDEX \`idx_documents_company_type_date\` ON \`documents\``);
        await queryRunner.query(`DROP INDEX \`idx_documents_customer\` ON \`documents\``);
        await queryRunner.query(`DROP TABLE \`documents\``);
        await queryRunner.query(`DROP TABLE \`series\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_ce25f853d71eb62860e58cc141\` ON \`establishments\``);
        await queryRunner.query(`DROP TABLE \`establishments\``);
        await queryRunner.query(`DROP INDEX \`IDX_1fe1a1fe5eaf15ada69b1b2e99\` ON \`companies\``);
        await queryRunner.query(`DROP TABLE \`companies\``);
        await queryRunner.query(`DROP TABLE \`tax_catalog\``);
        await queryRunner.query(`DROP TABLE \`perception_catalog\``);
        await queryRunner.query(`DROP TABLE \`detraction_catalog\``);
    }

}
